config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :payload_match_rules
  end

  resources :routes do
    collection do
      get :add_config
      delete :remove_config
      get :add_config_rule
      delete :remove_config_rule
      post :apply_config_rule
      get :add_filter
      delete :remove_filter
      get :add_filter_rule
      post :apply_filter_rule
      delete :remove_filter_rule
      post :add_service
      post :add_service_list
      post :edit_configurator
      post :add_configurator
      post :preview_configurator
    end
  end

  get 'pipeline/prebuilt', :to => 'routes#prebuilt', :as => :prebuilt_routes
  post 'pipeline/prebuilder', :to => 'routes#apply_prebuilt', :as => :apply_prebuilt_routes

  get 'pipeline/:pipeline_name/dashboard', :as => 'pipeline_dashboard', :to => 'routes#dashboard'

  # Repository hooking
  get 'pipeline(/:pipeline_name)/repositories', :as => 'pipeline_repositories', :to => 'route_repositories#list'
  post 'pipeline/repositories/:repository_id', :as => 'pipeline_repository_enable', :to => 'route_repositories#enable'
  delete 'pipeline/repositories/:repository_id', :as => 'pipeline_repository_disable', :to => 'route_repositories#disable'
  get 'pipeline/repositories/validate/:repository_id', :as => 'pipeline_repository_validate', :to => 'route_repositories#validate'
  get 'pipeline/repositories/reload', :as => 'pipeline_repositories_reload', :to => 'route_repositories#reload'

  # Job display
  get 'pipeline(/:pipeline_name)/jobs(/:payload_filter/:payload_value)', :to => 'route_jobs#all', :as => 'pipeline_jobs'
  get 'pipeline/job/:job_id', :to => 'route_jobs#details', :as => 'pipeline_job'
  get 'pipeline/job/:job_id/status', :to => 'route_jobs#job_status', :as => 'pipeline_job_status'
end

app/controllers/admin/payload_match_rules_controller.rb
class Admin::PayloadMatchRulesController < ApplicationController

  def index
    respond_to do |format|
      format.js do
        flash[:error] = 'Unsupported request!'
        javascript_redirect_to dashboard_path
      end
      format.html do
        @rules = PayloadMatchRule.order(:name).all
      end
    end
  end

  def new
    respond_to do |format|
      format.js do
        flash[:error] = 'Unsupported request!'
        javascript_redirect_to dashboard_url
      end
      format.html
    end
  end

  def create
    respond_to do |format|
      format.js do
        flash[:error] = 'Unsupported request!'
        javascript_redirect_to dashboard_url
      end
      format.html do
        begin
          PayloadMatchRule.new(
            :name => params[:name],
            :payload_key => params[:payload_key],
            :description => params[:description]
          ).save
          flash[:success] = 'New payload match rule created!'
        rescue => e
          Rails.logger.error "Failed to create PayloadMatchRule: #{e.class} - #{e}"
          Rails.logger.debug "#{e.class}: #{e}\n#{e.backtrace.join("\n")}"
          flash[:error] = "Failed to create payload match rule! (#{e})"
        end
        redirect_to admin_payload_match_rules_path
      end
    end
  end

  def edit
    respond_to do |format|
      format.js do
        flash[:error] = 'Unsupported request!'
        javascript_redirect_to dashboard_url
      end
      format.html do
        @rule = PayloadMatchRule.find_by_id(params[:id])
        unless(@rule)
          flash[:error] = 'Failed to locate requested payload match rule!'
          redirect_to admin_payload_match_rules_path
        end
      end
    end
  end

  def update
    respond_to do |format|
      format.js do
        flash[:error] = 'Unsupported request!'
        javascript_redirect_to dashboard_url
      end
      format.html do
        rule = PayloadMatchRule.find_by_id(params[:id])
        if(rule)
          rule.payload_key = params[:payload_key]
          rule.description = params[:description]
          begin
            rule.save
            flash[:success] = 'Payload match rule updated!'
          rescue => e
            Rails.logger.error "Failed to update PayloadMatchRule (#{rule}): #{e.class} - #{e}"
            Rails.logger.debug "#{e.class}: #{e}\n#{e.backtrace.join("\n")}"
            flash[:error] = "Failed to update payload match rule! (#{e})"
          end
        else
          flash[:error] = 'Failed to locate requested payload match rule!'
        end
        redirect_to admin_payload_match_rules_path
      end
    end
  end

  def destroy
    respond_to do |format|
      format.js do
        flash[:error] = 'Unsupported request!'
        javascript_redirect_to dashboard_url
      end
      format.html do
        rule = PayloadMatchRule.find_by_id(params[:id])
        if(rule)
          begin
            rule.destroy
            flash[:success] = 'Destroyed payload match rule!'
          rescue => e
            Rails.logger.error "Failed to destroy PayloadMatchRule (#{rule}): #{e.class} - #{e}"
            Rails.logger.debug "#{e.class}: #{e}\n#{e.backtrace.join("\n")}"
            flash[:error] = "Failed to destroy payload match rule! (#{e})"
          end
        else
          flash[:error] = 'Failed to locate requested payload match rule!'
        end
        redirect_to admin_payload_match_rules_path
      end
    end
  end

end

app/views/admin/payload_match_rules/_form.html.haml
= bootstrap_form_tag form_opts.merge(:html => {:id => 'payload-match-rule-form'}) do |f|
  = f.text_field :name, :value => @rule ? @rule.name : nil
  = f.text_field :description, :value => @rule ? @rule.description : nil
  = f.text_field :payload_key, :value => @rule ? @rule.payload_key : nil, :help => 'Snake cased key using double-underscore (__) to indicate Hash'
  = f.submit 'Save', :disable_with => 'Saving...', :class => 'btn btn-success'

app/views/admin/payload_match_rules/edit.html.haml
:ruby
  id = 'edit-payload-match-rule'
  content_for(:container) do
    render(
      :partial => 'layouts/panel',
      :locals => {
        :id => id,
        :heading => "Edit Payload Match Rule: #{@rule.name}",
        :panel_content => render(
          :partial => 'form',
          :locals => {
            :form_opts => {
              :url => admin_payload_match_rule_path(@rule.id),
              :method => :put
            }
          }
        )
      }
    )
  end

= render(:partial => 'layouts/container', :locals => {:container_class => "#{id}-form", :container_id => id})

app/views/admin/payload_match_rules/index.html.haml
- content_for(:heading_title) do
  = link_to('Create', new_admin_payload_match_rule_path, :class => 'btn btn-success btn-sm pull-right')
  .clearfix

:ruby
  id = 'payload-match-rule'
  content_for(:container) do
    render(
      :partial => 'layouts/panel',
      :locals => {
        :id => id,
        :heading => ('Payload Matching Rules' + yield(:heading_title)).html_safe,
        :panel_content => render(
          :partial => 'layouts/table',
          :locals => {
            :header_data => ['Matching Rules'],
            :data => @rules.map{|rule|
              [link_to(rule.name, edit_admin_payload_match_rule_path(rule.id))]
            }
          }
        )
      }
    )
  end

= render(:partial => 'layouts/container', :locals => {:container_class => "#{id}-list", :container_id => id})

app/views/admin/payload_match_rules/new.html.haml
:ruby
  id = 'new-payload-match-rule'
  content_for(:container) do
    render(
      :partial => 'layouts/panel',
      :locals => {
        :id => id,
        :heading => 'New Payload Match Rule',
        :panel_content => render(
          :partial => 'form',
          :locals => {
            :form_opts => {
              :url => admin_payload_match_rules_path,
              :method => :post
            }
          }
        )
      }
    )
  end

= render(:partial => 'layouts/container', :locals => {:container_class => "#{id}-form", :container_id => id})