config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :payload_match_rules
  end

  resources :routes do
    collection do
      get :add_config
      delete :remove_config
      get :add_config_rule
      delete :remove_config_rule
      post :apply_config_rule
      get :add_filter
      delete :remove_filter
      get :add_filter_rule
      post :apply_filter_rule
      delete :remove_filter_rule
      post :add_service
      post :add_service_list
      post :edit_configurator
      post :add_configurator
      post :preview_configurator
    end
  end

  get 'pipeline/prebuilt', :to => 'routes#prebuilt', :as => :prebuilt_routes
  post 'pipeline/prebuilder', :to => 'routes#apply_prebuilt', :as => :apply_prebuilt_routes

  get 'pipeline/:pipeline_name/dashboard', :as => 'pipeline_dashboard', :to => 'routes#dashboard'

  # Repository hooking
  get 'pipeline(/:pipeline_name)/repositories', :as => 'pipeline_repositories', :to => 'route_repositories#list'
  post 'pipeline/repositories/:repository_id', :as => 'pipeline_repository_enable', :to => 'route_repositories#enable'
  delete 'pipeline/repositories/:repository_id', :as => 'pipeline_repository_disable', :to => 'route_repositories#disable'
  get 'pipeline/repositories/validate/:repository_id', :as => 'pipeline_repository_validate', :to => 'route_repositories#validate'
  get 'pipeline/repositories/reload', :as => 'pipeline_repositories_reload', :to => 'route_repositories#reload'

  # Job display
  get 'pipeline(/:pipeline_name)/jobs(/:payload_filter/:payload_value)', :to => 'route_jobs#all', :as => 'pipeline_jobs'
  get 'pipeline/job/:job_id', :to => 'route_jobs#details', :as => 'pipeline_job'
  get 'pipeline/job/:job_id/status', :to => 'route_jobs#job_status', :as => 'pipeline_job_status'
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController

  before_action do
    if(params[:pipeline_name])
      pipeline = @account.routes_dataset.where(:name => params[:pipeline_name]).first
      if(pipeline && session[:route_id] != pipeline.id)
        session[:route_id] = pipeline.id
        redirect_to url_for(params)
      end
    end
  end

  def dashboard
    respond_to do |format|
      format.js do
        flash[:error] = 'Unsupported request!'
        javascript_redirect_to pipeline_dashboard_path
      end
      format.html do
        @route = @account.routes_dataset.where(:name => params[:pipeline_name]).first
      end
    end
  end

  def prebuilt
    respond_to do |format|
      format.js do
        flash[:error] = 'Unsupported request!'
        javascript_redirect_to pipeline_dashboard_path
      end
      format.html do
        @groups = ServiceGroup.all.find_all do |sg|
          sg.services.all? do |srv|
            @account.services.include?(srv)
          end
        end.sort_by(&:generated_cost).push(nil)
      end
    end
  end

  def apply_prebuilt
    respond_to do |format|
      format.js do
        flash[:error] = 'Unsupported request!'
        javascript_redirect_to pipeline_dashboard_path
      end
      format.html do
        group = ServiceGroup.all.find_all do |sg|
          sg.services.all? do |srv|
            @account.services.include?(srv)
          end
        end.detect do |sg|
          sg.id == params[:service_group_id].to_i
        end
        if(group)
          route = Route.create(
            :name => group.name,
            :account_id => @account.id,
            :description => group.description
          )
          group.services.each_with_index do |srv, idx|
            route.add_service(
              :service => srv,
              :position => idx
            )
          end
          group.service_group_payload_filters.each do |filter|
            r_filter = Fission::Data::Models::RoutePayloadFilter.find_or_create(
              :name => filter.name,
              :description => filter.description,
              :route_id => route.id
            )
            filter.payload_matchers.each do |matcher|
              new_matcher = Fission::Data::Models::PayloadMatcher.find_or_create(
                :value => matcher.value,
                :payload_match_rule_id => matcher.payload_match_rule_id,
                :account_id => @account.id
              )
              r_filter.add_payload_matcher(new_matcher)
            end
          end
          flash[:success] = 'New pipeline successfully created!'
          redirect_to pipeline_dashboard_path(:pipeline_name => route.name)
        else
          flash[:error] = 'Failed to locate requested pipeline for setup!'
          redirect_to prebuilt_routes_path
        end
      end
    end
  end

  def index
    respond_to do |format|
      format.js do
        flash[:error] = 'Unsupported request!'
        javascript_redirect_to dashboard_path
      end
      format.html do
        @routes = @account.routes
      end
    end
  end

  def show
    route = @account.routes_dataset.where(:id => params[:id]).first
    if(route)
      session[:route_id] = route.id
      flash[:success] = "Pipeline loaded: #{route.name}"
    else
      session.delete(:route_id)
      if(params[:id].to_i == 0)
        flash[:success] = 'Pipeline has been unset!'
      else
        flash[:error] = 'Failed to locate requested pipeline'
      end
    end
    respond_to do |format|
      format.js do
        javascript_redirect_to pipeline_jobs_path(:pipeline_name => route.name)
      end
      format.html do
        redirect_to pipeline_dashboard_path(:pipeline_name => route.name)
      end
    end
  end

  def new
    respond_to do |format|
      format.js do
        flash[:error] = 'Unsupported request!'
        javascript_redirect_to dashboard_path
      end
      format.html do
        @services = current_product_features.map(&:services).flatten.uniq.sort_by(&:name)
        @service_groups = current_product_features.map(&:service_groups).flatten.uniq.sort_by(&:name)
        @custom_services = @account.custom_services_dataset.order(:name).all
      end
    end
  end

  def create
    route = save_route!
    notify!(:create, :route => route)
    flash[:success] = 'Created new pipeline!'
    respond_to do |format|
      format.js do
        javascript_redirect_to routes_path
      end
      format.html do
        redirect_to routes_path
      end
    end
  end

  def edit
    respond_to do |format|
      format.js do
        flash[:error] = 'Unsupported request!'
        javascript_redirect_to dashboard_path
      end
      format.html do
        @route = @account.routes_dataset.where(:id => params[:id]).first
        unless(@route)
          flash[:error] = 'Failed to locate requested pipeline'
          redirect_to routes_path
        else
          @services = current_product_features.map(&:services).flatten.uniq.sort_by(&:name) - (@route.services || [])
          @service_groups = current_product_features.map(&:service_groups).flatten.uniq.sort_by(&:name) - (@route.service_groups || [])
          @custom_services = @account.custom_services_dataset.order(:name).all - (@route.custom_services || [])
          @configs = @account.account_configs_dataset.order(:name).all
          @match_rules = PayloadMatchRule.order(:name).all
        end
      end
    end
  end

  def update
    route = @account.routes_dataset.where(:id => params[:id]).first
    if(route)
      if(route.description != params[:description])
        route.description = params[:description]
        route.save
      end
      save_route!(route)
      notify!(:update, :route => route)
      flash[:success] = 'Updated pipeline!'
    else
      flash[:error] = 'Failed to locate requested pipeline!'
    end
    respond_to do |format|
      format.js do
        javascript_redirect_to routes_path
      end
      format.html do
        redirect_to routes_path
      end
    end
  end

  def destroy
    if(isolated_product?)
      flash[:error] = 'Invalid request! Cannot destroy product pipeline.'
    else
      route = @account.routes_dataset.where(:id => params[:id]).first
      if(route)
        name = route.name
        notify!(:destroy, :route => route) do
          route.destroy
        end
        flash[:success] = "Pipeline has been destroyed! (#{name})"
      else
        flash[:error] = 'Failed to located requested pipeline'
      end
    end
    respond_to do |format|
      format.js do
        javascript_redirect_to routes_path
      end
      format.html do
        redirect_to routes_path
      end
    end
  end

  # route config packs

  def add_config_rule
    respond_to do |format|
      format.js do
        @rule = PayloadMatchRule.find_by_id(params[:rule])
        @identifier = params[:identifier]
      end
      format.html do
        flash[:error] = 'Unsupported request!'
        redirect_to dashboard_path
      end
    end
  end

  def apply_config_rule
    respond_to do |format|
      format.js do
        @rule = PayloadMatchRule.find_by_id(params[:rule_id])
        @identifier = params[:identifier]
        @value = params[:value]
      end
      format.html do
        flash[:error] = 'Unsupported request!'
        redirect_to dashboard_path
      end
    end
  end

  def remove_config_rule
    respond_to do |format|
      format.js do
        @rule_ident = params[:rule_ident]
      end
      format.html do
        flash[:error] = 'Unsupported request!'
        redirect_to dashboard_path
      end
    end
  end

  def add_config
    respond_to do |format|
      format.js do
        @configs = @account.account_configs_dataset.order(:name).all
        @match_rules = PayloadMatchRule.order(:name).all
      end
      format.html do
        flash[:error] = 'Unsupported request!'
        redirect_to dashboard_path
      end
    end
  end

  def remove_config
    respond_to do |format|
      format.js do
        @ident = params[:ident]
      end
      format.html do
        flash[:error] = 'Unsupported request!'
        redirect_to dashboard_path
      end
    end
  end

  # route filters

  def add_filter_rule
    respond_to do |format|
      format.js do
        @rule = PayloadMatchRule.find_by_id(params[:rule])
        @identifier = params[:identifier]
      end
      format.html do
        flash[:error] = 'Unsupported request!'
        redirect_to dashboard_path
      end
    end
  end

  def apply_filter_rule
    respond_to do |format|
      format.js do
        @rule = PayloadMatchRule.find_by_id(params[:rule_id])
        @identifier = params[:identifier]
        @value = params[:value]
      end
      format.html do
        flash[:error] = 'Unsupported request!'
        redirect_to dashboard_path
      end
    end
  end

  def remove_filter_rule
    respond_to do |format|
      format.js do
        @rule_ident = params[:rule_ident]
      end
      format.html do
        flash[:error] = 'Unsupported request!'
        redirect_to dashboard_path
      end
    end
  end

  def add_filter
    respond_to do |format|
      format.js do
        @match_rules = PayloadMatchRule.order(:name).all
      end
      format.html do
        flash[:error] = 'Unsupported request!'
        redirect_to dashboard_path
      end
    end
  end

  def remove_filter
    respond_to do |format|
      format.js do
        @ident = params[:ident]
      end
      format.html do
        flash[:error] = 'Unsupported request!'
        redirect_to dashboard_path
      end
    end
  end

  def add_service
    respond_to do |format|
      format.js do
        params[:data] = params[:data].values.flatten.compact
        @items = Smash.new
        @items['Service'] = current_product_features.map(&:services).flatten.uniq.sort_by(&:name).find_all do |item|
          params[:data].any? do |x|
            x['type'] == item.class.to_s.split('::').last && x['id'] == item.id.to_s
          end
        end

app/views/routes/_prebuilt_item.html.haml
%p.lead.route-summary= group.description
.route-services.panel.panel-info
  .panel-heading
    Services
  %ul.list-group
    - group.services.each do |srv|
      %li.list-group-item{'data-container' => 'body', 'data-toggle' => 'popover', 'data-placement' => 'right', 'title' => srv.name.humanize, 'data-content' => srv.description, 'role' => 'button'}= srv.name
.row
  .col-md-4
  .col-md-4
    .panel.panel-success
      .panel-body.bg-success
        .route-price
          %center
            %b
              = "#{number_to_currency(group.generated_cost, :precision => 0, :locale => :en)}/mo"
  .col-md-4

app/views/routes/_route_builder_advanced.html.haml
.panel.panel-default#route-builder
  .panel-heading
    Route
  .panel-content
    .col-md-3.pull-left.route-items
      .panel.panel-success
        .panel-heading
          Route Items
        .panel-content
          %ul.list-group.bg-success.services-connector.service.custom-service.service-group#route-items{:style => 'list-style-type: none; min-height: 20px'}
            - if @route && @route.route_list
              - @route.route_list.each do |item|
                - if item.is_a?(Fission::Data::Models::Service)
                  %li.list-group-item.service{:item_type => 'service', :item_id => item.id, :style => 'background-color: #fcf8ec'}
                    = item.display_name.humanize
                    %i.fa.fa-question-circle.pull-right{'data-toggle' => 'tooltip', 'title' => item.description, 'data-placement' => 'right'}
                - elsif item.is_a?(Fission::Data::Models::ServiceGroup)
                  %li.list-group-item.bg-info.service-group{:item_type => 'service-group', :item_id => item.id, :style => 'background-color: #d9edf7'}= item.name
                - elsif item.is_a?(Fission::Data::Models::CustomService)
                  %li.list-group-item.bg-danger.custom-service{:item_type => 'custom-service', :item_id => item.id, :style => 'background-color: #f2dede'}= item.name
    .col-md-3.service-available-list
      .panel.panel-warning
        .panel-heading
          Available Services
        .panel-body
          %ul.list-group.bg-warning.services-connector.service#all-services{:style => 'list-style-type: none; min-height: 20px'}
            - @services.each do |service|
              %li.list-group-item.service{:item_type => 'service', :item_id => service.id, :style => 'background-color: #fcf8ec'}
                = service.display_name.humanize
                %i.fa.fa-question-circle.pull-right{'data-toggle' => 'tooltip', 'title' => service.description, 'data-placement' => 'right'}

    .col-md-3.service-group-available-list
      .panel.panel-info
        .panel-heading
          Available Service Groups
        .panel-body
          %ul.list-group.bg-info.services-connector.service-group#all-service-groups{:style => 'list-style-type: none; min-height: 20px'}
            - @service_groups.each do |service_group|
              %li.list-group-item.bg-info.service-group{:item_type => 'service-group', :item_id => service_group.id, :style => 'background-color: #d9edf7'}= service_group.name
    .col-md-3.custom-service-available-list
      .panel.panel-danger
        .panel-heading
          Custom Services
        .panel-content
          %ul.list-group.bg-danger.services-connector.custom-service#all-custom-services{:style => 'list-style-type: none; min-height: 20px'}
            - @custom_services.each do |custom_service|
              %li.list-group-item.bg-danger.custom-service{:item_type => 'custom-service', :item_id => custom_service.id, :style => 'background-color: #f2dede'}= custom_service.name
    .clearfix

app/views/routes/_route_builder_basic.html.haml
.panel.panel-default#route-builder
  .panel-heading
    Route
    .pull-right.route-item-adder= yield(:create_icon)
    .clearfix
  .panel-body
    = render :partial => 'route_collection', :locals => {:route_items => route_items}

app/views/routes/_route_config.html.haml
- suffix = SecureRandom.uuid if suffix.nil?
- config = nil unless defined?(config)
- configs = [] unless defined?(configs)

.panel.panel-default.route-config{:config_identifier => suffix, :id => suffix}
  .panel-heading
    = config ? "Configurator: #{config.name}" : 'New Configuration'
    .pull-right
      = link_to(yield(:edit_icon), "##{suffix}-body", 'aria-expanded' => false, 'data-toggle' => 'collapse', 'aria-controls' => "#{suffix}-body")
      - if config
        = link_to(yield(:delete_icon), '#', :class => 'window-rails', 'window-rails-ajax' => 'delete', 'window-rails-confirm' => "Delete #{config.name} configurator?", 'window-rails-title' => 'Remove Configurator', 'window-rails-url' => remove_config_routes_path(:ident => suffix))
      - else
        = link_to(yield(:delete_icon), remove_config_routes_path(:ident => suffix), :method => :delete, :remote => true)

  .panel-body.collapse{:id => "#{suffix}-body"}
    .form-group
      %label.control-label{:for => "#{suffix}-name"}
        Name
      %input.form-control{:type => 'text', :name => "#{suffix}-name", :value => config ? config.name : nil, :disabled => !!config, :id => "#{suffix}-name", :autofocus => 'autofocus'}
    .form-group
      %label.control-label{:for => "#{suffix}-description"}
        Description
      %input.form-control{:type => 'text', :name => "#{suffix}-description", :value => config ? config.description : nil, :id => "#{suffix}-description"}
    .col-md-6.pull-left
      .panel.panel-default
        .panel-heading
          Configuration Packs
        .panel-body
          .col-md-6.pull-left.config-pack
            .panel.panel-success
              .panel-heading
                Applied Packs
              .panel-body
                .list-group.bg-success{:id => "route-configs-#{suffix}", :style => 'list-style-type: none; min-height: 20px', :class => suffix}
                  - if config
                    - config.account_configs.each do |a_config|
                      %li.list-group-item{:config_id => a_config.id, :style => 'background-color: inherit'}= a_config.name
          .col-md-6.pull-left.config-items
            .panel.panel-danger
              .panel-heading
                Available Packs
              .panel-body
                %ul.list-group.bg-danger{:id => "available-configs-#{suffix}", :style => 'list-style-type: none; min-height: 20px', :class => suffix}
                  - (configs - (config ? config.account_configs : [])).each do |config|
                    %li.list-group-item{:config_id => config.id, :style => 'background-color: inherit'}= config.name
    .col-md-6
      .panel.panel-default{:id => SecureRandom.uuid}
        .panel-heading
          Configuration Apply Matchers
        .panel-body
          %table.table.table-striped{:id => "rules-#{suffix}"}
            - if config && config.payload_matchers
              - config.payload_matchers.each do |match|
                = render :partial => 'rule', :locals => {:rule => match.payload_match_rule, :value => match.value, :removal_link_method => :remove_config_rule_routes_path, :rule_type => 'config'}
          .dropdown.pull-right
            %button.btn.btn-primary{:id => 'drop', :type => 'button', 'data-toggle' => 'dropdown', 'aria-haspopup' => true, 'aria-expanded' => false}
              Add Match
              %span.caret
            %ul.dropdown-menu{:role => 'menu', 'aria-labelledby' => 'drop'}
              - rules.each do |rule|
                %li= link_to rule.name, add_config_rule_routes_path(:rule => rule.id, :identifier => suffix), :remote => true

    .clearfix
:javascript
  $(document).ready(
    function(){
      $("#route-configs-#{suffix}, #available-configs-#{suffix}").sortable({
        connectWith: ".#{suffix}"
      }).disableSelection();
      $('.route-config .panel-heading').hover(function(){ $(this).css('cursor', 'move'); }, function(){ $(this).css('cursor', 'auto'); });
    }
  );

app/views/routes/_route_config_rule.html.haml
%div.panel.panel-default
  %div.panel-body
    - if rule.description
      %div.well.well-sm= rule.description
    = bootstrap_form_tag :url => apply_config_rule_routes_path, :remote => true do |f|
      = f.text_field :value
      = f.hidden_field :rule_id, :value => rule.id
      = f.hidden_field :identifier, :value => identifier
      = f.submit 'Add', :disable_with => 'Add...', :class => 'btn btn-success pull-right'

app/views/routes/_rule.html.haml
- rule_ident = SecureRandom.uuid
- rule = @rule unless rule
- value = @value unless value

%tr{:class => "#{rule_type}-rule", :id => rule_ident, :rule_id => rule.id, :rule_value => value}
  %td
    %b= rule.name
  %td= value
  %td= link_to(yield(:delete_icon), send(removal_link_method, :rule_ident => rule_ident), :remote => true, :method => :delete)

app/views/routes/add_filter_rule.js.erb
<%=
  create_window(
    :name => 'filter_rule',
    :title => @rule.name,
    :content => render(
      :partial => 'rule_form',
      :locals => {
        :rule => @rule,
        :identifier => @identifier,
        :form_url => apply_filter_rule_routes_path
      }
    ),
    :auto_open => true
  )
%>

setTimeout(function(){$('#value').focus().select();}, 500);

app/views/routes/add_service_list.js.erb
<%=
  create_window(
    :name => 'service_add',
    :title => 'Add new route item',
    :size => 'normal',
    :content => render(
      :partial => 'service_list',
      :locals => {
        :services => @services,
        :service_groups => @service_groups,
        :custom_services => @custom_services
      }
    )
  )
%>

app/views/routes/apply_config_rule.js.erb
<%
content = render(
  :partial => 'rule',
  :locals => {
    :name => @rule.name,
    :value => @value
  }
)
%>
$('#rules-<%= @identifier -%>').append("<%= escape_javascript(content) -%>");
sparkle_ui.display.highlight($('#rules-<%= @identifier -%>').parents('.panel').first().attr('id'), 'success');
<%= close_window('config_rule') %>

app/views/routes/apply_filter_rule.js.erb
<%
content = render(
  :partial => 'rule',
  :locals => {
    :name => @rule.name,
    :value => @value,
    :removal_link_method => :remove_filter_rule_routes_path,
    :rule_type => 'filter'
  }
)
%>
$('#rules-<%= @identifier -%>').append("<%= escape_javascript(content) -%>");
sparkle_ui.display.highlight($('#rules-<%= @identifier -%>').parents('.panel').first().attr('id'), 'success');
<%= close_window('filter_rule') %>

app/views/routes/index.html.haml
- content_for(:heading_title) do
  = "Custom Routes for: #{@account.name}"
  = link_to('Create', new_route_path, :class => 'btn btn-sm btn-success pull-right')
  .clearfix

:ruby
  id = 'custom-routes'
  content_for(:container) do
    render(
      :partial => 'layouts/panel',
      :locals => {
        :id => id,
        :heading => yield(:heading_title),
        :panel_content => render(
          :partial => 'layouts/table',
          :locals => {
            :data => @routes.map{|route|
              [
                link_to(route.name, edit_route_path(route.id)),
                link_to(
                  yield(:delete_icon),
                  route_path(route.id),
                  :remote => true,
                  :method => :delete,
                  :class => 'pull-right'
                )
              ]
            }
          }
        ),
        :panel_class => 'widget'
      }
    )
  end

= render(:partial => 'layouts/container', :locals => {:container_class => "#{id}-list", :container_id => id})

app/views/routes/preview_configurator.js.erb
$('.configurator-preview').popover({
  content: "<pre><%= j(@configuration.html_safe) %></pre>",
  html: true,
  placement: 'right',
  title: 'Merged Configuration',
  trigger: 'focus'
});
$('.configurator-preview').popover('show');
$('.configurator-preview').on('hidden.bs.popover', function(){
  $(this).popover('destroy');
});

app/views/routes/remove_config_rule.js.erb
elm = $('#<%= @rule_ident -%>');
container_id = elm.parents('.panel').first().attr('id');
elm.remove();
sparkle_ui.display.highlight(container_id, 'danger');

app/views/routes/remove_filter_rule.js.erb
elm = $('#<%= @rule_ident -%>');
container_id = elm.parents('.panel').first().attr('id');
elm.remove();
sparkle_ui.display.highlight(container_id, 'danger');